### ISSUE TITLE
SyntaxError: only named arguments may follow *expression

### ISSUE THREAD

**Issue by wangyarui** [neocsr/semantic-segmentation#1]
when I run **python main.py**

Some errors occur like these:

Traceback (most recent call last):
  File "main.py", line 3, in <module>
    import helper
  File "/home/richal/code/CarND-Semantic-Segmentation/helper.py", line 91
    gt_bg = gt_bg.reshape(*gt_bg.shape, 1)
SyntaxError: only named arguments may follow *expression

But I have installed it by**sudo pip install helper**and **sudo pip install request**in fact. Please,help,thank U

**Comment by neocsr** [comment]
That looks like a python version issue. I'm using python 3.5.2 and tensorflow 1.3.0.
